//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColinaApplication.Data.Conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_FACTURAS_FALLIDAS_DIAN
    {
        public decimal ID { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<decimal> ID_SOLICITUD { get; set; }
        public string BODY_JSON { get; set; }
        public string ERROR { get; set; }
    }
}
