//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColinaApplication.Data.Conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CLIENTES_DIAN
    {
        public decimal ID { get; set; }
        public string TIPO_PERSONA { get; set; }
        public string CODIGO_DOCUMENTO { get; set; }
        public string NOMBRE_DOCUMENTO { get; set; }
        public string NUMERO_IDENTIFICACION { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public string NOMBRE_COMERCIAL { get; set; }
        public string DIRECCION { get; set; }
        public string COD_CIUDAD { get; set; }
        public string NOM_CIUDAD { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> RESPONSABLE_IVA { get; set; }
        public string CODIGO_R_FISCAL { get; set; }
        public string NOMBRE_R_FISCAL { get; set; }
        public string ID_CODIGO_DIAN { get; set; }
        public string TELEFONO { get; set; }
        public string DIGITO_VERIFI { get; set; }
    }
}
